### ISSUE TITLE
Showing strictmode policy error

### ISSUE THREAD

**Issue by bharathnr21** [dkrivoruchko/ScreenStream#20]
E/StrictMode: null
                                                                    java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
                                                                        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2010)
                                                                        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
                                                                        at sun.nio.ch.Net.socket0(Native Method)
                                                                        at sun.nio.ch.Net.serverSocket(Net.java:424)
                                                                        at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
                                                                        at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
                                                                        at io.netty.channel.socket.nio.NioServerSocketChannel.newSocket(NioServerSocketChannel.java:58)
                                                                        at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:71)
                                                                        at java.lang.Class.newInstance(Native Method)
                                                                        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
                                                                        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
                                                                        at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
                                                                        at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
                                                                        at io.reactivex.netty.protocol.tcp.server.TcpServerImpl.start(TcpServerImpl.java:198)
                                                                        at io.reactivex.netty.protocol.http.server.HttpServerImpl.start(HttpServerImpl.java:181)
                                                                        at info.dvkr.screenstream.domain.httpserver.HttpServerImpl.<init>(HttpServerImpl.kt:162)
                                                                        at info.dvkr.screenstream.data.presenter.foreground.FgPresenter$1.doResume(FgPresenter.kt:61)
                                                                        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                                                                        at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                        at java.lang.Thread.run(Thread.java:764)

**Comment by dkrivoruchko** [comment]
What android version?

**Comment by bharathnr21** [comment]
Android 8.0.0

On Mar 14, 2018 1:43 PM, "Dmitriy Krivoruchko" <notifications@github.com>
wrote:

What android version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dkrivoruchko/ScreenStream/issues/20#issuecomment-372937709>,
or mute the thread

**Comment by dkrivoruchko** [comment]
You may ignore it.

**Comment by bharathnr21** [comment]
Thanks for response!

But Once the service, after 2-3 minutes, service is getting crashed.

I am getting the below warning and in the browser it is showing the blank
screen.

 W/DisplayManagerService: Failed to notify process 3116 that displays
changed, assuming it died.

android.os.DeadObjectException
                                                            at
android.os.BinderProxy.transactNative(Native Method)
                                                            at
android.os.BinderProxy.transact(Binder.java:787)
                                                            at
android.hardware.display.IDisplayManagerCallback$Stub$Proxy.onDisplayEvent(IDisplayManagerCallback.java:81)
                                                            at
com.android.server.display.DisplayManagerService$CallbackRecord.notifyDisplayEventAsync(DisplayManagerService.java:1479)
                                                            at
com.android.server.display.DisplayManagerService.deliverDelayDisplayEvent(DisplayManagerService.java:1393)
                                                            at
com.android.server.display.DisplayManagerService.-wrap7(Unknown Source:0)
                                                            at
com.android.server.display.DisplayManagerService$DisplayManagerHandler.handleMessage(DisplayManagerService.java:1375)
                                                            at
android.os.Handler.dispatchMessage(Handler.java:105)
                                                            at
android.os.Looper.loop(Looper.java:164)
                                                            at
android.os.HandlerThread.run(HandlerThread.java:65)
                                                            at
com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by dkrivoruchko** [comment]
I can not  reproduce this error. Are you using latest app version?
