### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' 

### ISSUE THREAD

**Issue by rufan-nativesol** [dkrivoruchko/ScreenStream#269]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
       at java.lang.Class.isAssignableFrom(Class.java:824)
       at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4853)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
       at android.os.Parcel.readValue(Parcel.java:4532)
       at android.os.Parcel.readValue(Parcel.java:4312)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
       at android.os.BaseBundle.getValue(BaseBundle.java:374)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.BaseBundle.get(BaseBundle.java:696)
       at android.os.Bundle.getParcelable(Bundle.java:947)
       at android.content.Intent.getParcelableExtra(Intent.java:8902)
       at info.dvkr.screenstream.mjpeg.internal.MjpegEvent$Intentable$Companion.fromIntent$mjpeg_release(MjpegEvent.java:70)
       at info.dvkr.screenstream.mjpeg.MjpegModuleService.onStartCommand(MjpegModuleService.kt:70)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4721)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7937)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

**Comment by rufan-nativesol** [comment]
Like?
![device](https://github.com/user-attachments/assets/ae1e1ab4-2024-4ba2-a1ce-b34ce24ad5fd)
![trace](https://github.com/user-attachments/assets/037b04af-417c-4263-b9e8-3788a7bb14ad)

**Comment by dkrivoruchko** [comment]
This is not helpful, as you just send the same error as an image.
It's really hard to tell what is wrong. It can be some Gradle config issue or DI issue or just device specific.

**Comment by rufan-nativesol** [comment]
This is my first time, so I'm unsure what details I need to send you. Please let me know what you need to know to resolve this issue. Thanks.

**Comment by dkrivoruchko** [comment]
In that case, the best option is to put your project on GitHub public repo and put link to it here.
